spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: pass
  liquibase:
    change-log: classpath:db/changelog/changelog.xml
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: false

logging:
  level:
    org.hibernate.SQL: DEBUG
